Id: Adobe.Brackets
Name: Brackets
AppMoniker: brackets.io
Version: 1.14.2
Publisher: Adobe
Author: Adobe
License: MIT License
LicenseUrl: https://github.com/microsoft/msix-packaging/blob/master/LICENSE
MinOSVersion: 10.0.0.0
Homepage: http://brackets.io/
Tags: "brackets"
InstallerType: msi
 
# ======================= Installers  ================== 
 
Installers: 
  - Arch: x64
    Url: https://github.com/adobe/brackets/releases/download/release-1.14.2/Brackets.Release.1.14.2.msi
    Sha256: 5F059E271FE78FEFE224E187B6EF559445B1EFADD6DCA9446A99CA1A53EB4E56
    Language: en-US
    Scope: user
    Switches: 
      Custom: /QUIET /NORESTART