Id: dropbox.dropbox
Name: Dropbox
AppMoniker: Dropbox
Version: 94.4.384
Publisher: Dropbox
Author: Dropbox
License: MIT License
LicenseUrl: https://github.com/microsoft/msix-packaging/blob/master/LICENSE
MinOSVersion: 10.0.0.0
Homepage: https://www.dropbox.com
Tags: "cloud,online,storage,dropbox,pictures,files"
InstallerType: exe


# ======================= Installers  ================== 

Installers: 
  - Arch: x64 
    Url: https://clientupdates.dropboxstatic.com/dbx-releng/client/Dropbox%2094.4.384%20Offline%20Installer.exe
    Sha256:  69193537721AD4E10C4B264C5AFA9AEB10E73657B82BE38D629D05A5765F8C1F
    Switches: 
      Silent: /s
      SilentWithProgress: /s
