Id: 7zip.7zip
Name: 7Zip
AppMoniker: 7zip
Version: 16.0.4
Publisher: 7zip
Author: 7zip
License: MIT License
LicenseUrl: https://github.com/microsoft/msix-packaging/blob/master/LICENSE
MinOSVersion: 10.0.0.0
Homepage: https://www.7-zip.org/
Tags: "7zip,compression,file compression,utility,tool,zip"
InstallerType: msi


# ======================= Installers  ================== 

Installers: 
  - Arch: x64 
    Url: https://www.7-zip.org/a/7z1604-x64.msi
    Sha256:  B3885B2F090F1E9B5CF2B9F802B07FE88E472D70D60732DB9F830209AC296067 
