Id: Geany.Geany
Name: Geany
AppMoniker: 4315aadhilrf.geany_hqkbg2ta66qf0
Version: 1.36
Publisher: Geany
Author: Geany
License: MIT License
LicenseUrl: https://github.com/microsoft/msix-packaging/blob/master/LICENSE
MinOSVersion: 10.0.0.0
Homepage: https://www.geany.org/download/releases/
Tags: "editor,Geany,texteditor"
InstallerType: Nullsoft
# ======================= Installers  ================== 
Installers: 
  - Arch: x64 
    Url: https://download.geany.org/geany-1.36_setup.exe
    Sha256: 1549B62F9E9FDDE825AE45245BAFC3A47CE85F4555F28B06E3A9C600340751DF