Id: Atom.Atom
Name: Atom
AppMoniker: atom.exe
Version: 1.45.0
Publisher: Atom
Author: Atom
License: MIT License
LicenseUrl: https://github.com/microsoft/msix-packaging/blob/master/LICENSE
MinOSVersion: 10.0.0.0
Homepage: https://atom.io/
Tags: "atom,texteditor,IDE"
InstallerType: exe
# ======================= Installers  ================== 
Installers: 
  - Arch: x64 
    Url: https://atom.io/download/windows_x64
    Sha256: 2A234BCEF846D35A50E50516B000788AC63715E5B320AAACDA5193947B1EFF3C
    Switches: 
      Silent: "/VERYSILENT /NORESTART /ALLUSERS"
      SilentWithProgress: "/VERYSILENT /NORESTART /ALLUSERS"