Id: WiresharkFoundation.Wireshark
Version: 3.2.2
Name: Wireshark
Publisher: WiresharkFoundation
Homepage: https://www.wireshark.org/
License: The license under which Wireshark is issued is the GNU General Public License version 2. 
LicenseUrl: https://www.gnu.org/licenses/gpl-2.0.html
Description: Wireshark is the world's foremost and widely-used network protocol analyzer. It lets you see what's happening on your network at a microscopic level and is the de facto (and often de jure) standard across many commercial and non-profit enterprises, government agencies, and educational institutions.
# SystemAppId: Wireshark
Installers: 
    - Arch: x86
      Url: https://1.na.dl.wireshark.org/win32/Wireshark-win32-3.2.2.exe
      InstallerType: Nullsoft
      Sha256: 73af61a1edae2af371e432a09bbda8af48a8ada0ea789592ff24499d80070ae6

