Id: Bluefish.Bluefish
Name: Bluefish
AppMoniker: bluefish.exe
Version: 2.2.11
Publisher: Bluefish
Author: Bluefish
License: MIT License
LicenseUrl: https://github.com/microsoft/msix-packaging/blob/master/LICENSE
MinOSVersion: 10.0.0.0
Homepage: http://bluefish.openoffice.nl/download.html
Tags: "bluefish,texteditor"
InstallerType: Inno
 
# ======================= Installers  ================== 
 
Installers: 
  - Arch: x64
    Url: https://www.bennewitz.com/bluefish/stable/binaries/win32/Bluefish-2.0.0-1-setup.exe
    Sha256: 7CA2B97B60B9E94F8AB08B6BCD82A148D66492EF7742C32A6F7D6B37B43BDC2D
    Language: en-US
    Scope: user