Id: gimp.gimp
Name: GIMP
AppMoniker: gimp
Version: 2.10.16
Publisher: gimp
Author: gimp
License: MIT License
LicenseUrl: https://github.com/microsoft/msix-packaging/blob/master/LICENSE
MinOSVersion: 10.0.0.0
Homepage: https://www.gimp.com
Tags: "editor,image,picture,pictures,photo,gimp"
InstallerType: exe


# ======================= Installers  ================== 

Installers: 
  - Arch: x64 
    Url: https://download.gimp.org/mirror/pub/gimp/v2.10/windows/gimp-2.10.16-setup.exe
    Sha256: B68ABECDCA74B1F118FA88848DBA323A4145918C9D2D89CDD886C3D8B203C52C
    Switches: 
      Silent: "/VERYSILENT /NORESTART /ALLUSERS"
      SilentWithProgress: "/VERYSILENT /NORESTART /ALLUSERS"