Id: gimp.gimp
Name: GIMP
AppMoniker: gimp
Version: 2.10.10
Publisher: gimp
Author: gimp
License: MIT License
LicenseUrl: https://github.com/microsoft/msix-packaging/blob/master/LICENSE
MinOSVersion: 10.0.0.0
Homepage: https://www.gimp.com
Tags: "editor,image,picture,pictures,photo,gimp"
InstallerType: exe


# ======================= Installers  ================== 

Installers: 
  - Arch: x64 
    Url: https://download.gimp.org/mirror/pub/gimp/v2.10/windows/gimp-2.10.10-setup.exe
    Sha256: C20024CCE6A04005C1A515CF189339E30DC4B0115EAEC37BA4B639B2F0D06FCA
    Switches: 
      Silent: "/VERYSILENT /NORESTART /ALLUSERS"
      SilentWithProgress: "/VERYSILENT /NORESTART /ALLUSERS"