Id: gimp.gimp
Name: GIMP
AppMoniker: gimp
Version: 2.10.0
Publisher: gimp
Author: gimp
License: MIT License
LicenseUrl: https://github.com/microsoft/msix-packaging/blob/master/LICENSE
MinOSVersion: 10.0.0.0
Homepage: https://www.gimp.com
Tags: "editor,image,picture,pictures,photo,gimp"
InstallerType: exe


# ======================= Installers  ================== 

Installers: 
  - Arch: x64 
    Url: https://download.gimp.org/mirror/pub/gimp/v2.10/windows/gimp-2.10.0-setup.exe
    Sha256: F4E8FC7813A0B5A797F614D25400EB829C3238546D7FC5940B60553DC46937CA
    Switches: 
      Silent: "/VERYSILENT /NORESTART /ALLUSERS"
      SilentWithProgress: "/VERYSILENT /NORESTART /ALLUSERS"