Id: gimp.gimp
Name: GIMP
AppMoniker: gimp
Version: 2.10.14
Publisher: gimp
Author: gimp
License: MIT License
LicenseUrl: https://github.com/microsoft/msix-packaging/blob/master/LICENSE
MinOSVersion: 10.0.0.0
Homepage: https://www.gimp.com
Tags: "editor,image,picture,pictures,photo,gimp"
InstallerType: exe


# ======================= Installers  ================== 

Installers: 
  - Arch: x64 
    Url: https://download.gimp.org/mirror/pub/gimp/v2.10/windows/gimp-2.10.14-setup-1.exe
    Sha256: DDC8F6AE9A7FB2625B72149CAA31113FC275F9B49105B3E96F89FB4164F1EFE6
    Switches: 
      Silent: "/VERYSILENT /NORESTART /ALLUSERS"
      SilentWithProgress: "/VERYSILENT /NORESTART /ALLUSERS"