Id: gimp.gimp
Name: GIMP
AppMoniker: gimp
Version: 2.10.12
Publisher: gimp
Author: gimp
License: MIT License
LicenseUrl: https://github.com/microsoft/msix-packaging/blob/master/LICENSE
MinOSVersion: 10.0.0.0
Homepage: https://www.gimp.com
Tags: "editor,image,picture,pictures,photo,gimp"
InstallerType: exe


# ======================= Installers  ================== 

Installers: 
  - Arch: x64 
    Url: https://download.gimp.org/mirror/pub/gimp/v2.10/windows/gimp-2.10.12-setup-1.exe
    Sha256: 1E624AC9F082ED7FA7DADF67C249A6AA7C208E156A7D92CFF63437E63A644BFB
    Switches: 
      Silent: "/VERYSILENT /NORESTART /ALLUSERS"
      SilentWithProgress: "/VERYSILENT /NORESTART /ALLUSERS"